title: Material Design
theme: jekyll-material-github-theme
branch: main
include:
  - _wiki
  - LICENSE.md
exclude:
  - .idea/
  - package.json
  - LICENSE
  - Gemfile
  - jekyll-material-github-theme.gemspec
